rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  strict: 0
parser: babel-eslint
ecmaFeatures:
  modules: true
  arrowFunctions: true
env:
  es6: true
  node: true
extends: 'eslint:recommended'

